# Generated by Django 3.2.5 on 2021-08-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlineTest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='marks',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
